name: CodSpeed

on:
  push:
    branches: ["main"]
  pull_request:
  workflow_dispatch:

permissions:
  contents: read
  id-token: write

jobs:
  benchmarks:
    uses: jcfangc/ci/.github/workflows/rust-codspeed.yml@ccd19196bcd8e8a42924c0621c321ee2dc2db61a
    with:
      rust_toolchain: "1.98.1"
      cargo_codspeed_version: "5.0.1"
      runner: ubuntu-24.04
      build_command: RUSTFLAGS="-C target-feature=+avx2" cargo codspeed build -m simulation
      run_command: cargo codspeed run -m simulation ours_
